### ISSUE TITLE
1.8.8 support?

### ISSUE THREAD

**Issue by TheIronMinerLv** [AgentManny/LunarClientAPI#2]
yo,

Soo there are ways to support 1.7 clients on 1.8.8 spigot servers. It seems like this API doesn't load on such version
`Error occurred while enabling LunarClientAPI v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelHandler
	at gg.manny.lunar.LunarClientAPI.onEnable(LunarClientAPI.java:34) ~[lunar-client-api-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot1.8.8:git-paperspigot-bf053c8d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:360) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:319) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:417) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:381) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:336) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:269) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:572) [paperspigot1.8.8:git-paperspigot-bf053c8d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelHandler
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[paperspigot1.8.8:git-paperspigot-bf053c8d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paperspigot1.8.8:git-paperspigot-bf053c8d]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 12 more`

I'm using paperspigot 1.8.8, please fix ty

**Comment by AgentManny** [comment]
I don't provide support for this API anymore. I recommend you compiling it and re-importing since 1.8.8 spigots doesn't shade the netty library
